### ISSUE TITLE
発見した問題色々

### ISSUE THREAD

**Issue by Soviet-Stalin** [polyacetal/e-auto_ReBuild#28]
･BeautifulSoupのparserがlxmlになっているが､HTMLなのでhtml.parserを使うべき
･問題文に-(ハイフン)が入ると無限ループに入ってしまう
･答えを間違えて記録してしまうことがある
･並べ替え問題の答えの中に,(カンマ)が入ると､そのカンマの前後が別々の選択肢として扱われる
･選択肢をデータベースに保存する必要はないのでは?

**Comment by Soviet-Stalin** [comment]
プルリク:
https://github.com/polyacetal/e-auto_ReBuild/pull/24

**Comment by yugu0202** [comment]
#### 一番目の問題について
lxmlのほうが速いので採用してます bs4の標準パーサですし、特に問題はないかと
#### 二番目の問題について
問題文に"-"が入ると無限ループする件に関しては変更点が多すぎてこちらで修正内容が確認取れていないため対応しかねております
#### 三番目の問題について
答えを間違えて記録する問題は答えが空になってしまう問題とは別でしょうか？
#### 四番目の問題について
","が入ると別々の選択肢として扱われる問題に関しては失念していました、修正します
#### 五番目の問題について
日本文と英文も一緒の可能性を考慮して選択肢で保存しています(ex."can" or "be able to"が並べ替え問題でくっついた選択肢として用意されている可能性)

**Comment by WinLinux1028** [comment]
3: 多分同じなのでこのissueでは統一した
4: 俺の修正版では区切り文字を🤔に変更した

**Comment by Soviet-Stalin** [comment]
3: 多分同じなのでこのissueでは統一した
4: 俺の修正版では区切り文字を､恐らく使われないであろう文字の🤔に変更した

**Comment by yugu0202** [comment]
二番目って解答で無限ループしていますか？

**Comment by yugu0202** [comment]
そもそも、どの行数でinputタグの取得をしていらっしゃるのですか？

**Comment by Soviet-Stalin** [comment]
> 二番目って解答で無限ループしていますか？
1. question_text取得時に-が消去されるが､DBに記録するときには-が入った状態になってるのでDBのデータと一致しない
2. dont knowになる
3. 解答欄がaで埋め尽くされ不正解になる
4. 1に戻る
> lxmlに関して
これに関しては俺が独自で追加した部分(リスニング対応のところ)
https://github.com/Soviet-Stalin/e-auto_ReBuild/blob/d197c4d2b4f40c6907a5c94fd2d4b00ff76f9f2d/eAuto.py#L214
リスニング問題ではblanked_textの中に､閉じタグのないinputタグが存在していて､そのせいでlxmlではtextを取得できない
html.parserにすれば問題なく動く

**Comment by Soviet-Stalin** [comment]
![名称未設定](https://user-images.githubusercontent.com/98158575/150629578-9707ee7e-50c2-4f20-873a-a595fdba5682.png)

**Comment by yugu0202** [comment]
> > 二番目って解答で無限ループしていますか？
> 
> 1. question_text取得時に-が消去されるが､DBに記録するときには-が入った状態になってるのでDBのデータと一致しない
> 2. dont knowになる
> 3. 解答欄がaで埋められ不正解になる
> 4. 1に戻る
> 
> > lxmlに関して
> 
> これに関しては俺が独自で追加した部分(リスニング対応のところ) https://github.com/Soviet-Stalin/e-auto_ReBuild/blob/d197c4d2b4f40c6907a5c94fd2d4b00ff76f9f2d/eAuto.py#L214 リスニング問題ではblanked_textの中に､閉じタグのないinputタグが存在していて､そのせいでlxmlではtextを取得できない html.parserにすれば問題なく動く

あれなんでre.subしてるんだろう…

lxmlに関してなんですが、空所記入と形は同じなのに取得できないということでよろしいでしょうか？
