### ISSUE TITLE
回答自動回収機能の追加

### ISSUE THREAD

**Issue by polyacetal** [polyacetal/e-auto_ReBuild#4]
各問題に合わせた形式で問題文及びその解答を回収する

**Comment by yugu0202** [comment]
回答収集は各問題に合わせた形式ではなく全文回収すると同じ文で形の違う問題にも対応可能だと思います

**Comment by polyacetal** [comment]
その件については#6の解決が先決です
解決までしばしお待ちを

**Comment by polyacetal** [comment]
#6 での話がまとまったため作業を開始します
